### ISSUE TITLE
Path to sendToCodecov.io.js

### ISSUE THREAD

**Issue by kytwb** [cainus/codecov.io#10]
If using the binary `./node_modules/.bin/codecov`, there's a path issue:

```
11-May-2015 15:55:42	module.js:340
11-May-2015 15:55:42	    throw err;
11-May-2015 15:55:42	          ^
11-May-2015 15:55:42	Error: Cannot find module '../lib/sendToCodeCov.io'
11-May-2015 15:55:42	    at Function.Module._resolveFilename (module.js:338:15)
11-May-2015 15:55:42	    at Function.Module._load (module.js:280:25)
11-May-2015 15:55:42	    at Module.require (module.js:364:17)
11-May-2015 15:55:42	    at require (module.js:380:17)
11-May-2015 15:55:42	    at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/REAC-RCSW-UT/node_modules/.bin/codecov:2:21)
11-May-2015 15:55:42	    at Module._compile (module.js:456:26)
11-May-2015 15:55:42	    at Object.Module._extensions..js (module.js:474:10)
11-May-2015 15:55:42	    at Module.load (module.js:356:32)
11-May-2015 15:55:42	    at Function.Module._load (module.js:312:12)
11-May-2015 15:55:42	    at Function.Module.runMain (module.js:497:10)
```

Using directly `./node_modules/codecov.io/bin/codecov.io.js` fix this.

**Comment by stevepeak** [comment]
@cainus can you help out with this one. Thanks!
