### ISSUE TITLE
Error from codecov finding lcov.info in windows

### ISSUE THREAD

**Issue by magestican** [cainus/codecov.io#23]
I am getting this error in windows because of the way the find command uses its dashes and cant get past it and it is crashing my build :

C:\callscreen\coverage\PhantomJS 2.0.0 (Windows 8 0.0.0)>codecov

---

 / ____|        | |
| |     ___   **| | ___  ___ ___**   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |**_| (_) | (_| |  __/ (_| (_) \ V /
 ___**_**/ \**,_|___|_**_**/ _/
                                v1.0.1
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration:
    Endpoint: https://codecov.io
{ commit: '1ed0fcce4fab96b2367937a986bea916021491e3',
  branch: 'develop',
  token: 'asdasd',
  package: 'node-v1.0.1' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '_.gcno'  -exec gcov  {} +
File not found - '_.gcno'
    Failed to run gcov command.
==> Scanning for reports
FIND: Parameter format not correct
child_process.js:484
    throw err;
    ^

Error: Command failed: find . -type f ( -name '_coverage._' -or -name 'nosetests.xml' -or -name 'jacoco_.xml' -or -name 'clover.xml' -or -name 'report.xml' -or -name 'cobertura.xml' -or -name 'luacov.report.out' -or -name 'lcov.info' -or -name '_.lcov' -or -name 'gcov.info' -or -name '_.gcov' -or -name '_.lst' ) -not -name '_.sh' -not -name '_.data' -not -name '_.py' -not -name '_.class' -not -name '_.xcconfig' -not -name 'Coverage.profdata' -not -name 'phpunit-code-coverage.xml' -not -name 'coverage.serialized' -not -name '_.pyc' -not -name '_.cfg' -not -name '_.egg' -not -name '_.whl' -not -name '_.html' -not -name '_.js' -not -name '_.cpp' -not -name 'coverage.jade' -not -name 'include.lst' -not -name 'inputFiles.lst' -not -name 'createdFiles.lst' -not -name 'coverage.html' -not -name 'scoverage.measurements._' -not -name 'test___coverage.txt' -not -path '_/vendor/_' -not -path '_/htmlcov/_' -not -path '_/home/cainus/_' -not -path '_/virtualenv/_' -not -path '_/js/generated/coverage/_' -not -path '_/.virtualenv/_' -not -path '_/virtualenvs/_' -not -path '_/.virtualenvs/_' -not -path '_/.env/_' -not -path '_/.envs/_' -not -path '_/env/_' -not -path '_/envs/_' -not -path '_/.venv/_' -not -path '_/.venvs/_' -not -path '_/venv/_' -not -path '_/venvs/_' -not -path '_/.git/_' -not -path '_/.hg/_' -not -path '_/.tox/_' -not -path '*/__pycache__/_' -not -path '_/.egg-info_' -not -path '_/$bower_components/_' -not -path '_/node_modules/_' -not -path '_/conftest_*.c.gcov'
FIND: Parameter format not correct

```
at checkExecSyncError (child_process.js:441:13)
at execSync (child_process.js:481:13)
at Object.upload (C:\Users\AA Admin\AppData\Roaming\npm\node_modules\codecov\lib\codecov.js:260:18)
at Object.<anonymous> (C:\Users\AA Admin\AppData\Roaming\npm\node_modules\codecov\bin\codecov:24:9)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:475:10)
at startup (node.js:117:18)
```

Do you have a workaround for this or a parameter I can pass the file path on or something?

**Comment by stevepeak** [comment]
Hey @magestican, sorry I did not reply earlier didn't see this :(

This is related to https://github.com/codecov/codecov-node/issues/8 which will be fixed soon. Thanks!

**Comment by luismichel** [comment]
I am still having this problem with codecov 2.1.0

``` / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                v2.1.0
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration:
    Endpoint: https://codecov.io
{ commit: '3d7ae0b2aa10fa0be1384658f485ec80288f1f8c',
  branch: 'develop',
  token: 'abc123',
  package: 'node-v2.1.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '*.gcno'  -exec gcov  {} +
File not found - '*.gcno'
    Failed to run gcov command.
'test' is not recognized as an internal or external command,
operable program or batch file.
==> Scanning for reports
FIND: Parameter format not correct
child_process.js:526
    throw err;
    ^

Error: Command failed: find . -type f \( -name '*coverage.*' -or -name 'nosetests.xml' -or -name 'jacoco*.xml' -or -name 'clover.xml' -or -name 'report.xml' -or -name 'cobertura.xml' -or -name 'luacov.report.out' -or -name 'lcov.info' -or -name '*.lcov' -or -name 'gcov.info' -or -name '*.gcov' -or -name '*.lst' \) -not -name '*.sh' -not -name '*.data' -not -name '*.py' -not -name '*.class' -not -name '*.xcconfig' -not -name 'Coverage.profdata' -not -name 'phpunit-code-coverage.xml' -not -name 'coverage.serialized' -not -name '*.pyc' -not -name '*.cfg' -not -name '*.egg' -not -name '*.whl' -not -name '*.html' -not -name '*.js' -not -name '*.cpp' -not -name 'coverage.jade' -not -name 'include.lst' -not -name 'inputFiles.lst' -not -name 'createdFiles.lst' -not -name 'coverage.html' -not -name 'scoverage.measurements.*' -not -name 'test_*_coverage.txt' -not -path '*/vendor/*' -not -path '*/htmlcov/*' -not -path '*/home/cainus/*' -not -path '*/virtualenv/*' -not -path '*/js/generated/coverage/*' -not -path '*/.virtualenv/*' -not -path '*/virtualenvs/*' -not -path '*/.virtualenvs/*' -not -path '*/.env/*' -not -path '*/.envs/*' -not -path '*/env/*' -not -path '*/envs/*' -not -path '*/.venv/*' -not -path '*/.venvs/*' -not -path '*/venv/*' -not -path '*/venvs/*' -not -path '*/.git/*' -not -path '*/.hg/*' -not -path '*/.tox/*' -not -path '*/__pycache__/*' -not -path '*/.egg-info*' -not -path '*/$bower_components/*' -not -path '*/node_modules/*' -not -path '*/conftest_*.c.gcov'
FIND: Parameter format not correct

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at Object.upload (C:\Users\Luis Michel\dev\service-pnr-ui\node_modules\codecov\lib\codecov.js:264:18)
    at Object.<anonymous> (C:\Users\Luis Michel\dev\service-pnr-ui\node_modules\codecov\bin\codecov:25:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm ERR! Test failed.  See above for more details.```

Is there a workaround or a fix that I might have missed?

**Comment by stevepeak** [comment]
@eddiemoore thoughts?
