### ISSUE TITLE
upload fails

### ISSUE THREAD

**Issue by tcurdt** [cainus/codecov.io#28]
I am trying to test the upload manually

    export CODECOV_TOKEN="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    cat ./coverage/lcov.info | ./node_modules/.bin/codecov

but I am getting

    node_modules/codecov.io/lib/getConfiguration.js:27
              throw new Error("unknown service. could not get configuration");
              ^

        Error: unknown service. could not get configuration
            at module.exports (node_modules/codecov.io/lib/getConfiguration.js:27:13)
            at sendToCodecov (node_modules/codecov.io/lib/sendToCodeCov.io.js:11:15)
            at Socket.<anonymous> (node_modules/codecov.io/bin/codecov.io.js:14:5)
            at emitNone (events.js:72:20)
            at Socket.emit (events.js:166:7)
            at endReadableNT (_stream_readable.js:903:12)
            at doNTCallback2 (node.js:439:9)
            at process._tickCallback (node.js:353:17)

**Comment by stevepeak** [comment]
Looks like Codecov is being ran from an unknown location. It needs to gather some extra information, like the list of files in git, to properly map the coverage reports back.

Can you provide me with more details on how and where you are running the uploader. Thank you!

**Comment by tcurdt** [comment]
Have a look here https://github.com/tcurdt/xstatic/blob/master/package.json
Running

    npm run coverage
    export CODECOV_TOKEN="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    cat ./coverage/lcov.info | ./node_modules/.bin/codecov

should reproduce the problem.

**Comment by stevepeak** [comment]
Hey @tcurdt this package does not support uploading from outside a supported CI provider. You can use one of the following to upload anywhere:
- https://github.com/codecov/codecov-bash
- https://github.com/codecov/codecov-python
